version: '3'
services:
  jupyterlab:
    build: .
    working_dir: /workspace
    volumes:
      - ..:/workspace
    ports:
      - "8888:8888"
    command: >
      jupyter-lab
        --ip 0.0.0.0
        --allow-root
        -b localhost
        --no-browser
        --NotebookApp.token=''
        --notebook-dir=/workspace
